### ISSUE TITLE
Instant send - Send Preview sends an email successfully with a 200 OK response, but displays an error message

### ISSUE THREAD

**Issue by cjg89** [UCF/GMUCF-Utilities#3]
**Describe the bug**

See title.  Issue ported over from email editor plugin.

**Steps to Reproduce**

1. Set up a new email post in QA and assign at least one preview recipient
2. Click "Send Preview"
3. Instead of a success banner, a warning banner with "There was a problem sending the preview." appears
4. However, when inspecting the outbound request in the console, a 200 OK response is returned

**Expected Behavior**

When the preview sends as expected, a success message should appear.

**Possible Fix**

n/a

**Your environment:**

n/a

**Additional context**

n/a

**Comment by jmbarne3** [comment]
Leaving open until merged into master.
